### ISSUE TITLE
How to make slave node join with master node automatically

### ISSUE THREAD

**Issue by gogotaro** [beamsorrasak/jenkins-do-iac#1]
slave-init.sh -> script about wait for master node ready and get secret of slave node.

Need to find solution about replace string "ipv4AddressPrivate", "jenkinsUser", "jenkinsPassword" in slave-init.sh with cloud-init.

**Comment by beamsorrasak** [comment]
```
sed -i 's/ipv4AddressPrivate/${_dropletMaster.ipv4AddressPrivate}/' /root/slave-init.sh
sed -i 's/jenkinsUser/${config.misc.jenkinsUser}/' /root/slave-init.sh
sed -i 's/jenkinsPassword/${config.misc.jenkinsPassword}/' /root/slave-init.sh
bash /root/slave-init.sh
```

Script runcmd of cloud-init of slave machine.

**Comment by beamsorrasak** [comment]
```
[sed,-i,'s/ipv4AddressPrivate/${_dropletMaster.ipv4AddressPrivate}/',/root/slave-init.sh]
[sed,-i,'s/jenkinsUser/${config.misc.jenkinsUser}/',/root/slave-init.sh]
[sed,-i,'s/jenkinsPassword/${config.misc.jenkinsPassword}/',/root/slave-init.sh]
```
Use these instead of above but ipv4addressPrivate still not working.

**Comment by beamsorrasak** [comment]
It's working with ` _dropletMaster.ipv4AddressPrivate.apply(masterIP => ` to wait until masterIP was ready before get value of it.
